apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: itgo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: itgo
    app.kubernetes.io/part-of: byoc-app-czwk
  name: itgo
spec:
  rules:
  - host: itgo-byoc-jwqo-tenant.apps.709ff2c31487908948f2.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: itgo
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
